apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: alaudaSyncImage
  annotations:
    alauda.io/displayName.zh-CN: 同步镜像
    alauda.io/displayName.en: Sync Image
    alauda.io/description.zh-CN: 同步镜像模板。将一个镜像从源仓库同步到目标仓库。若源镜像或目标镜像仓库为私有仓库（内网地址），需确保 Jenkins 服务与其在同一网络环境内，方可使用。
    alauda.io/description.en: Sync image template. Synchronize a Image tag from the source repository to the target repository. If the source image or target image repository is a private repository (intranet address), ensure that Jenkins services are available in the same network.
    alauda.io/readme.zh-CN: 
    alauda.io/readme.en: 
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    category: syncImage
spec:
  engine: graph
  withSCM: false
  agent:
    label: docker
  options:
    timeout: 3600
  stages:
    - name: SyncImage
      tasks:
        - name: SyncImage
          type: public/alaudasyncimage
          approve:
            message: "是否要真的同步镜像"
            timeout: 3600 
  arguments:
    - displayName:
        zh-CN: "镜像信息"
        en: "Image Info"
      items:
        - name: sourceImage
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - SyncImage.args.sourceImage
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "源镜像仓库地址"
              en: "Address of source image repository"
            description:
              zh-CN: "同步镜像时，源镜像若为平台镜像，可直接选择；若为第三方镜像，需手动输入第三方镜像仓库地址，如：index.docker.io/alauda/hello-world"
              en: "When synchronizing the images, select the source images directly if the images are platform images. If the source images are third party images, you must enter the third party repository address, for example, index.docker.io/alauda/hello-world"
          required: true
        - name: "sourceImageTag"
          schema:
            type: string
          binding:
            - SyncImage.args.sourceImageTag
          display:
            type: string
            name:
              zh-CN: "源镜像版本"
              en: "Source image tag"
            description:
              zh-CN: "同步镜像时，源镜像的版本，如：latest"
              en: "When synchronizing the images, enter the version of the source image, for example, latest."
          required: true
          default: latest
        - name: sourceImageRegistryCredentialsId
          schema:
            type: string
          binding:
            - SyncImage.args.sourceImageRegistryCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            name:
              zh-CN: "源镜像凭据"
              en: "Source image registry credentials"
            description:
              zh-CN: "若源镜像仓库为有身份验证的第三方仓库，则需要使用凭据。可直接选择凭据，或为其添加新凭据"
              en: "If the source repository is an authenticated third party repository, you must use credentials. You can directly select an added credential or add new ones."
          required: false
        - name: image
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - SyncImage.args.image
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "目标镜像仓库地址"
              en: "Address of target image repository"
            description:
              zh-CN: "同步镜像时，目标镜像若为平台镜像，可直接选择；若为第三方镜像，需手动输入第三方镜像仓库地址，如：index.docker.io/alauda/hello-world"
              en: "When synchronizing the images, select the target images directly if the images are platform images. If the source images are third party images, you must enter the third party repository address, for example, index.docker.io/alauda/hello-world."
          required: true
        - name: "imageTag"
          schema:
            type: string
          binding:
            - SyncImage.args.imageTag
          display:
            type: string
            name:
              zh-CN: "目标镜像版本"
              en: "Target image tag"
            description:
              zh-CN: "同步镜像时，源镜像的版本，如：latest"
              en: "When synchronizing the images, enter the version of the source image, for example, latest. "
          required: true
          default: latest
        - name: imageRegistryCredentialsId
          schema:
            type: string
          binding:
            - SyncImage.args.imageRegistryCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            name:
              zh-CN: "目标镜像凭据"
              en: "Target image registry credentials"
            description:
              zh-CN: "源镜像仓库为有身份验证的第三方仓库，则需要使用凭据。可直接选择凭据，或为其添加新凭据"
              en: "If the source repository is an authenticated third party repository, you must use credentials. You can directly select an added credential or add new ones."
          required: false
