
apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: alaudasyncimage
  annotations:
    alauda.io/displayName.zh-CN: 同步镜像
    alauda.io/displayName.en: SyncImage
    alauda.io/description.zh-CN: 同步镜像
    alauda.io/description.en: SyncImage
    alauda.io/readme.zh-CN: 同步镜像
    alauda.io/readme.en: SyncImage
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    catgory: CI
    author: zpyu
spec:
  engine: gotpl
  body: |+
    script{
          {{- if .sourceusexsit}}
              def Image = "{{.sourceAlaimage.registry}}/{{.sourceAlaimage.repository}}:{{.sourceimageTag}}"
              def Registory = "{{.sourceAlaimage.registry}}"
          {{- else}}
              def Image = "{{.registory}}/{{.sourceimage}}:{{.sourcetag}}"
              def Registory = "{{.registory}}"
          {{- end}}
          {{- if .usexsit}}
              def TargetImage = "{{.image.registry}}/{{.image.repository}}:{{.imageTag}}"
              def TargetRegistory = "{{.image.registry}}"
          {{- else}}
              def TargetImage = "{{.targetregistory}}/{{.targetimage}}:{{.targettag}}"
              def TargetRegistory = "{{.targetregistory}}"
          {{- end}}
          {{- if .sourceimageRegistryCredentialsId}}
              withCredentials([usernamePassword(credentialsId: "{{.sourceimageRegistryCredentialsId}}", usernameVariable: "USERNAME", passwordVariable: "PASSWORD")]){
                  sh "docker login ${Registory} -u ${USERNAME} -p ${PASSWORD}"
          {{end}}
              sh "docker pull ${Image}"
              sh "docker tag ${Image} ${TargetImage}"
              {{- if .imageRegistryCredentialsId}}
                  withCredentials([usernamePassword(credentialsId: "{{.imageRegistryCredentialsId}}", usernameVariable: "USERNAME", passwordVariable: "PASSWORD")]){
                    sh "docker login ${TargetRegistory} -u ${USERNAME} -p ${PASSWORD}"
                  }
              {{- end}}
              sh "docker push ${TargetImage}"
          {{- if .sourceimageRegistryCredentialsId}}
          }
          {{- end}}
    }
  arguments:
    - name: sourceusexsit
      schema:
        type: boolean
      display:
        type: boolean
        name:
          zh-CN: "使用平台镜像"
          en: "Use image on platform"
        description:
          zh-CN: "源镜像使用平台镜像"
          en: "if enabled use image on platform to sync image"
      default: true
      required: false

    - name: "sourceAlaimage"
      schema:
        type: alauda.io/imagerepositorymix
      display:
        type: alauda.io/imagerepositorymix
        name:
          zh-CN: "源镜像仓库"
          en: "source image repository"
        description:
          zh-CN: "使用该源镜像仓库中的镜像去更新镜像"
          en: "use image in this repository to sync image"
      required: false
      relation:
        - action: show
          when:
            name: sourceusexsit
            value: true
    - name: "sourceimageTag"
      schema:
        type: string
      display:
        type: alauda.io/imagetag
        name:
          zh-CN: "源镜像版本"
          en: "Image Tag"
        description:
          zh-CN: "使用该源镜像版本去更新镜像"
          en: "image tag that will update to"
        related: sourceAlaimage
      required: false
      default: latest
      relation:
        - action: show
          when:
            name: sourceusexsit
            value: true
    - name: "registory"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "源镜像源地址"
          en: "Registory"
        description:
          zh-CN: "用户更新镜像时使用的源镜像registory地址"
          en: "Address of your image registory"
      required: false
      relation:
        - action: show
          when:
            name: sourceusexsit
            value: false    
    - name: "sourceimage"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "源镜像仓库"
          en: "sourceimage"
        description:
          zh-CN: "更新镜像使用的源镜像仓库"
          en: "Image registory to Sync image"
      required: true
      relation:
        - action: show
          when:
            name: sourceusexsit
            value: false
    - name: "sourcetag"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "源镜像标签"
          en: "sourcetag"
        description:
          zh-CN: "更新镜像使用的源镜像标签"
          en: "source iamge tag"
      required: true
      relation:
        - action: show
          when:
            name: sourceusexsit
            value: false
    - name: usexsit
      schema:
        type: boolean
      display:
        type: boolean
        name:
          zh-CN: "更新平台镜像"
          en: "sync the image on platform"
        description:
          zh-CN: "是否更新本平台镜像"
          en: "if enabled will sync image on platform"
      default: true
      required: false
    - name: "image"
      schema:
        type: alauda.io/imagerepositorymix
      display:
        type: alauda.io/imagerepositorymix
        name:
          zh-CN: "目标镜像仓库"
          en: "Target image respository"
        description:
          zh-CN: "目标镜像仓库"
          en: "Which image repository used to sync image"
      required: false
      relation:
        - action: show
          when:
            name: usexsit
            value: true
    - name: "imageTag"
      schema:
        type: string
      display:
        type: alauda.io/imagetag
        name:
          zh-CN: "目标镜像标签"
          en: "Target image tag"
        description:
          zh-CN: "更新后的目标镜像标签"
          en: "Image tag that will sync to "
        related: image
      required: false
      default: latest
      relation:
        - action: show
          when:
            name: usexsit
            value: true
    - name: "targetregistory"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "目标镜像源"
          en: "TargetRegistory"
        description:
          zh-CN: "目标镜像仓库源"
          en: "Address of your resource image registory"
      required: false
      relation:
        - action: show
          when:
            name: usexsit
            value: false  
    - name: "targetimage"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "目标镜像仓库"
          en: "targetimage"
        description:
          zh-CN: "目标镜像仓库"
          en: "image repository that will sync to"
      required: true
      relation:
        - action: show
          when:
            name: usexsit
            value: false
    - name: "targettag"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "目标镜像标签"
          en: "targettag"
        description:
          zh-CN: "目标镜像标签"
          en: "image tag that will sync to"
      required: false
      relation:
        - action: show
          when:
            name: usexsit
            value: false
    - name: imageRegistryCredentialsId
      schema:
        type: string
      display:
        type: alauda.io/jenkinscredentials
        name:
          zh-CN: "目标镜像registry凭据"
          en: "registry credential"
      required: false
    - name: sourceimageRegistryCredentialsId
      schema:
        type: string
      display:
        type: alauda.io/jenkinscredentials
        name:
          zh-CN: "源镜像registry凭据"
          en: "source registry credential"
      required: false











