apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: alaudasyncimage
  annotations:
    alauda.io/displayName.zh-CN: 同步镜像
    alauda.io/displayName.en: SyncImage
    alauda.io/description.zh-CN: 同步镜像模板。将一个镜像从源仓库同步到目标仓库。若源镜像或目标镜像仓库为私有仓库（内网地址），需确保 Jenkins 服务与其在同一网络环境内，方可使用。
    alauda.io/description.en: Sync image template. Synchronize a Image tag from the source repository to the target repository. If the source image or target image repository is a private repository (intranet address), ensure that Jenkins services are available in the same network.
    alauda.io/readme.zh-CN: 
    alauda.io/readme.en: 
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    catgory: syncImage
spec:
  engine: gotpl
  body: |+
    script{
          def Image = "{{.sourceImage.registry}}/{{.sourceImage.repository}}:{{.sourceImageTag}}"
          def Registory = "{{.sourceImage.registry}}"
          def TargetImage = "{{.image.registry}}/{{.image.repository}}:{{.imageTag}}"
          def TargetRegistory = "{{.image.registry}}"

          {{- if .sourceImageRegistryCredentialsId}}
              withCredentials([usernamePassword(credentialsId: "{{.sourceImageRegistryCredentialsId}}", usernameVariable: "USERNAME", passwordVariable: "PASSWORD")]){
                  sh "echo ${PASSWORD} > ./SourcePassWord"
                  sh "cat ./SourcePassWord|docker login ${Registory}  --username ${USERNAME} --password-stdin"
          {{end}}
              retry(2){
                  sh "docker pull ${Image}"
              }
              sh "docker tag ${Image} ${TargetImage}"
              {{- if .imageRegistryCredentialsId}}
                  withCredentials([usernamePassword(credentialsId: "{{.imageRegistryCredentialsId}}", usernameVariable: "TARGETUSERNAME", passwordVariable: "TARGETPASSWORD")]){
                    sh "echo ${TARGETPASSWORD} > ./PassWord"
                    sh "cat ./PassWord|docker login ${TargetRegistory}  --username ${TARGETUSERNAME} --password-stdin"
                  }
              {{- end}}
              retry(2){
                sh "docker push ${TargetImage}"
              }
          {{- if .sourceImageRegistryCredentialsId}}
          }
          {{- end}}
    }
  arguments:
    - name: "sourceImage"
      schema:
        type: alauda.io/imagerepositorymix
      display:
        type: alauda.io/imagerepositorymix
        name:
          zh-CN: "源镜像仓库地址"
          en: "Address of source Image repository"
        description:
          zh-CN: "同步镜像时，源镜像若为平台镜像，可直接选择；若为第三方镜像，需手动输入第三方镜像仓库地址，如：index.docker.io/alauda/hello-world"
          en: "When synchronizing the images, select the source images directly if the images are platform images. If the source images are third party images, you must enter the third party repository address, for example, index.docker.io/alauda/hello-world"
      required: false
    - name: "sourceImageTag"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "源镜像版本"
          en: "Source image tag"
        description:
          zh-CN: "同步镜像时，源镜像的版本，如：latest"
          en: "When synchronizing the images, enter the version of the source image, for example, latest."
        related: sourceImage
      required: false
      default: latest
    - name: "image"
      schema:
        type: alauda.io/imagerepositorymix
      display:
        type: alauda.io/imagerepositorymix
        name:
          zh-CN: "目标镜像仓库地址"
          en: "Address of target image repository"
        description:
          zh-CN: "同步镜像时，目标镜像若为平台镜像，可直接选择；若为第三方镜像，需手动输入第三方镜像仓库地址，如：index.docker.io/alauda/hello-world"
          en: "When synchronizing the images, select the target images directly if the images are platform images. If the source images are third party images, you must enter the third party repository address, for example, index.docker.io/alauda/hello-world."
      required: false
    - name: "imageTag"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "目标镜像版本"
          en: "Target image tag"
        description:
          zh-CN: "同步镜像时，源镜像的版本，如：latest"
          en: "When synchronizing the images, enter the version of the source image, for example, latest.  "
        related: image
      required: false
      default: latest
    - name: imageRegistryCredentialsId
      schema:
        type: string
      display:
        type: alauda.io/jenkinscredentials
        name:
          zh-CN: "目标镜像凭据"
          en: "Target image registry credential"
      required: false
    - name: sourceImageRegistryCredentialsId
      schema:
        type: string
      display:
        type: alauda.io/jenkinscredentials
        name:
          zh-CN: "源镜像凭据"
          en: "Source image registry credentials"
      required: false
